/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */


import http from 'http';

import localVarRequest from 'request';
/* tslint:disable:no-unused-locals */
import { TestEntityAddress } from '../model/testEntityAddress';

import { HttpError } from './apis';

import { ObjectSerializer, Authentication, VoidAuth, Interceptor } from '../model/models';
let defaultBasePath = 'http://localhost';

// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================

export enum TestEntityAddressApiApiKeys {
}

export class TestEntityAddressApi {
	protected _basePath = defaultBasePath;
	protected _defaultHeaders : any = {};
	protected _useQuerystring : boolean = false;

	protected authentications = {
		'default': <Authentication>new VoidAuth(),
	}

	protected interceptors: Interceptor[] = [];

	constructor(basePath?: string);
	constructor(basePathOrUsername: string, password?: string, basePath?: string) {
		if (password) {
			if (basePath) {
				this.basePath = basePath;
			}
		} else {
			if (basePathOrUsername) {
				this.basePath = basePathOrUsername
			}
		}
	}

	set useQuerystring(value: boolean) {
		this._useQuerystring = value;
	}

	set basePath(basePath: string) {
		this._basePath = basePath;
	}

	set defaultHeaders(defaultHeaders: any) {
		this._defaultHeaders = defaultHeaders;
	}

	get defaultHeaders() {
		return this._defaultHeaders;
	}

	get basePath() {
		return this._basePath;
	}

	public setDefaultAuthentication(auth: Authentication) {
		this.authentications.default = auth;
	}

	public setApiKey(key: TestEntityAddressApiApiKeys, value: string) {
		(this.authentications as any)[TestEntityAddressApiApiKeys[key]].apiKey = value;
	}

	public addInterceptor(interceptor: Interceptor) {
		this.interceptors.push(interceptor);
	}

	/**
	 * 
	 * @param testEntityId 
	 */
	public async getTestEntityTestEntityAddress (testEntityId: number, options: {headers: {[name: string]: string}} = {headers: {}}) : Promise<{ response: http.IncomingMessage; body: TestEntityAddress; }> {
		const localVarPath = this.basePath + '/test/v1.0/test-entities/{testEntityId}/test-entity-address'.replace('{' + 'testEntityId' + '}', encodeURIComponent(String(testEntityId)));
		let localVarQueryParameters: any = {};
		let localVarHeaderParams: any = (<any>Object).assign({}, this._defaultHeaders);
		const produces = ['application/json', 'application/xml'];
		// give precedence to 'application/json'
		if (produces.indexOf('application/json') >= 0) {
			localVarHeaderParams.Accept = 'application/json';
		} else {
			localVarHeaderParams.Accept = produces.join(',');
		}
		let localVarFormParams: any = {};

		// verify required parameter 'testEntityId' is not null or undefined
		if (testEntityId === null || testEntityId === undefined) {
			throw new Error('Required parameter testEntityId was null or undefined when calling getTestEntityTestEntityAddress.');
		}

		(<any>Object).assign(localVarHeaderParams, options.headers);

		let localVarUseFormData = false;

		let localVarRequestOptions: localVarRequest.Options = {
			method: 'GET',
			qs: localVarQueryParameters,
			headers: localVarHeaderParams,
			uri: localVarPath,
			useQuerystring: this._useQuerystring,
			json: true,
		};

		let authenticationPromise = Promise.resolve();
		authenticationPromise = authenticationPromise.then(() => this.authentications.default.applyToRequest(localVarRequestOptions));

		let interceptorPromise = authenticationPromise;
		for (const interceptor of this.interceptors) {
			interceptorPromise = interceptorPromise.then(() => interceptor(localVarRequestOptions));
		}

		return interceptorPromise.then(() => {
			if (Object.keys(localVarFormParams).length) {
				if (localVarUseFormData) {
					(<any>localVarRequestOptions).formData = localVarFormParams;
				} else {
					localVarRequestOptions.form = localVarFormParams;
				}
			}
			return new Promise<{ response: http.IncomingMessage; body: TestEntityAddress; }>((resolve, reject) => {
				localVarRequest(localVarRequestOptions, (error, response, body) => {
					if (error) {
						reject(error);
					} else {
						if (response.statusCode && response.statusCode >= 200 && response.statusCode <= 299) {
							body = ObjectSerializer.deserialize(body, "TestEntityAddress");
							resolve({ response: response, body: body });
						} else {
							reject(new HttpError(response, body, response.statusCode));
						}
					}
				});
			});
		});
	}
}