##
## Source Check Properties
##

    source.check.GradleDependencyArtifactsCheck.allowedVersionArtifacts=\
        org.springframework.boot:spring-boot-starter-oauth2-client,\
        org.springframework.boot:spring-boot-starter-oauth2-resource-server,\
        org.springframework.boot:spring-boot-starter-web,\
        org.springframework.boot:spring-boot-starter-webflux