/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.portal.tools.rest.builder.internal.typescript;

import com.liferay.petra.string.StringBundler;
import com.liferay.petra.string.StringPool;
import com.liferay.portal.kernel.util.HashMapBuilder;
import com.liferay.portal.kernel.util.ListUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.portal.kernel.util.Validator;
import com.liferay.portal.tools.rest.builder.internal.freemarker.tool.FreeMarkerTool;
import com.liferay.portal.tools.rest.builder.internal.freemarker.tool.java.JavaMethodSignature;
import com.liferay.portal.tools.rest.builder.internal.freemarker.tool.java.parser.ResourceOpenAPIParser;
import com.liferay.portal.tools.rest.builder.internal.freemarker.tool.java.parser.util.OpenAPIParserUtil;
import com.liferay.portal.tools.rest.builder.internal.freemarker.util.FreeMarkerUtil;
import com.liferay.portal.tools.rest.builder.internal.util.FileUtil;
import com.liferay.portal.tools.rest.builder.internal.yaml.config.ConfigYAML;
import com.liferay.portal.tools.rest.builder.internal.yaml.openapi.Components;
import com.liferay.portal.tools.rest.builder.internal.yaml.openapi.Content;
import com.liferay.portal.tools.rest.builder.internal.yaml.openapi.Discriminator;
import com.liferay.portal.tools.rest.builder.internal.yaml.openapi.Items;
import com.liferay.portal.tools.rest.builder.internal.yaml.openapi.OpenAPIYAML;
import com.liferay.portal.tools.rest.builder.internal.yaml.openapi.Operation;
import com.liferay.portal.tools.rest.builder.internal.yaml.openapi.Parameter;
import com.liferay.portal.tools.rest.builder.internal.yaml.openapi.PathItem;
import com.liferay.portal.tools.rest.builder.internal.yaml.openapi.RequestBody;
import com.liferay.portal.tools.rest.builder.internal.yaml.openapi.Response;
import com.liferay.portal.tools.rest.builder.internal.yaml.openapi.ResponseCode;
import com.liferay.portal.tools.rest.builder.internal.yaml.openapi.Schema;

import java.io.File;

import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Iterator;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Set;

/**
 * @author Daniel Raposo
 */
public class TypeScriptClientUtil {

	public static void generateTypeScriptClient(
			File configDir, ConfigYAML configYAML, File copyrightFile,
			String yamlString)
		throws Exception {

		File baseClientDir = new File(
			StringUtil.removeLast(configDir.getPath(), "-impl") + "-client-js");
		List<File> files = new ArrayList<>();

		_createBuildGradleFile(baseClientDir, files);
		_createNodeScriptsConfigFile(baseClientDir, files);
		_createPackageJSONFile(baseClientDir, files);

		OpenAPIYAML openAPIYAML = OpenAPIParserUtil.loadOpenAPIYAML(
			_addAutogeneratedVulcanSchemas(configYAML, yamlString));

		Map<String, Map<String, Object>> apiContexts = _buildAPIContexts(
			configYAML, openAPIYAML);

		for (Map.Entry<String, Map<String, Object>> apiContext :
				apiContexts.entrySet()) {

			_createFile(
				apiContext.getValue(), configYAML, copyrightFile, files,
				"typescript/api",
				StringBundler.concat(
					baseClientDir.getPath(), "/src/node/api/",
					StringUtil.lowerCaseFirstLetter(apiContext.getKey()),
					"Api.ts"));
		}

		_createFile(
			null, configYAML, copyrightFile, files, "typescript/api_global",
			baseClientDir.getPath() + "/src/node/api.ts");
		_createFile(
			Collections.singletonMap("apisContext", apiContexts.values()),
			configYAML, copyrightFile, files, "typescript/apis",
			baseClientDir.getPath() + "/src/node/api/apis.ts");

		Components components = openAPIYAML.getComponents();

		Map<String, Schema> schemas = components.getSchemas();

		if (schemas != null) {
			for (Map.Entry<String, Schema> entry : schemas.entrySet()) {
				_createFile(
					_buildModelContext(entry.getKey(), entry.getValue()),
					configYAML, copyrightFile, files, "typescript/model",
					StringBundler.concat(
						baseClientDir.getPath(), "/src/node/model/",
						StringUtil.lowerCaseFirstLetter(entry.getKey()),
						".ts"));
			}
		}

		_createFile(
			Collections.singletonMap("schemaMap", schemas), configYAML,
			copyrightFile, files, "typescript/models",
			baseClientDir.getPath() + "/src/node/model/models.ts");

		FileUtil.deleteFiles(baseClientDir.getPath(), files);
	}

	private static String _addAutogeneratedVulcanSchemas(
			ConfigYAML configYAML, String yamlString)
		throws Exception {

		OpenAPIYAML openAPIYAML = OpenAPIParserUtil.loadOpenAPIYAML(yamlString);
		Set<String> processedSchemaNames = new HashSet<>();

		FreeMarkerTool freeMarkerTool = FreeMarkerTool.getInstance();

		Map<String, Schema> schemas = freeMarkerTool.getSchemas(openAPIYAML);

		for (String schemaName : schemas.keySet()) {
			List<JavaMethodSignature> javaMethodSignatures =
				freeMarkerTool.getResourceJavaMethodSignatures(
					configYAML, openAPIYAML, schemaName);

			for (JavaMethodSignature javaMethodSignature :
					ResourceOpenAPIParser.
						getResourceGetPageJavaMethodSignatures(
							javaMethodSignatures)) {

				String returnType = StringUtil.removeSubstrings(
					javaMethodSignature.getReturnType(),
					"com.liferay.portal.vulcan.pagination.Page<", ">");

				String returnSchemaName = StringUtil.extractLast(
					returnType, ".");

				if (processedSchemaNames.add(returnSchemaName)) {
					if (processedSchemaNames.add("Facet")) {
						yamlString = _addSchema(
							FreeMarkerUtil.processTemplate(
								null, null, "facet_yaml", null),
							yamlString);
					}

					yamlString = _addSchema(
						FreeMarkerUtil.processTemplate(
							null, null, "page_yaml",
							HashMapBuilder.<String, Object>put(
								"schemaName", returnSchemaName
							).build()),
						yamlString);

					if (StringUtil.equals(
							"com.liferay.portal.vulcan.permission.Permission",
							returnType)) {

						yamlString = _addSchema(
							FreeMarkerUtil.processTemplate(
								null, null, "permission_yaml", null),
							yamlString);
					}
				}

				int index = StringUtil.indexOfAny(
					yamlString,
					new String[] {
						"\"" + javaMethodSignature.getPath() + "\":",
						" " + javaMethodSignature.getPath() + ":"
					});

				String httpMethod = OpenAPIParserUtil.getHTTPMethod(
					javaMethodSignature.getOperation());

				index = yamlString.indexOf(httpMethod + ":", index);

				String oldYAMLString = yamlString.substring(
					index, yamlString.indexOf("tags:", index));

				String newYAMLString = oldYAMLString.replaceAll(
					StringBundler.concat(
						"schema:\n([ \t]+)items:\n[ \t]+",
						"\\$ref: \"#/components/schemas/", returnSchemaName,
						"\"\n[ \t]+type: array"),
					StringBundler.concat(
						"schema:\n$1\\$ref: \"#/components/schemas/Page",
						returnSchemaName, "\""));

				yamlString = StringUtil.replace(
					yamlString, oldYAMLString, newYAMLString);
			}
		}

		return yamlString;
	}

	private static String _addSchema(
		String schemaYAMLString, String yamlString) {

		schemaYAMLString = StringUtil.replace(
			schemaYAMLString, new String[] {"$", "\t", "\n"},
			new String[] {"\\$", "$1", "\n$1$1"});

		return yamlString.replaceAll(
			"([ \\t]+)schemas:", "$1schemas:\n$1$1" + schemaYAMLString);
	}

	private static Map<String, Map<String, Object>> _buildAPIContexts(
		ConfigYAML configYAML, OpenAPIYAML openAPIYAML) {

		Map<String, PathItem> pathItems = openAPIYAML.getPathItems();

		Map<String, List<Map<String, Object>>> tagOperationsData =
			new HashMap<>();

		for (Map.Entry<String, PathItem> entry : pathItems.entrySet()) {
			for (Operation operation :
					OpenAPIParserUtil.getOperations(entry.getValue())) {

				List<String> tags = operation.getTags();

				List<Map<String, Object>> operationsData =
					tagOperationsData.computeIfAbsent(
						tags.get(0), k -> new ArrayList<>());

				operationsData.add(
					_buildOperationDataMap(
						configYAML, openAPIYAML, operation, entry.getKey()));
			}
		}

		Map<String, Map<String, Object>> apiContexts = new HashMap<>();

		for (Map.Entry<String, List<Map<String, Object>>> entry :
				tagOperationsData.entrySet()) {

			apiContexts.put(
				entry.getKey(),
				HashMapBuilder.<String, Object>put(
					"classname", entry.getKey() + "Api"
				).put(
					"imports",
					() -> {
						Set<Map<String, String>> allImports =
							new LinkedHashSet<>();

						for (Map<String, Object> operationData :
								entry.getValue()) {

							if (operationData.containsKey("imports")) {
								Collection<Map<String, String>> imports =
									(Collection<Map<String, String>>)
										operationData.remove("imports");

								allImports.addAll(imports);
							}
						}

						if (!allImports.isEmpty()) {
							return allImports;
						}

						return null;
					}
				).put(
					"operationsData", entry.getValue()
				).build());
		}

		return apiContexts;
	}

	private static Map<String, Object> _buildModelContext(
		String modelName, Schema schema) {

		Set<Map<String, String>> imports = new HashSet<>();
		String parentClass = null;
		List<Map<String, Object>> schemaProperties = new ArrayList<>();

		if (schema.getAllOfSchemas() != null) {
			List<Schema> allOfSchemas = schema.getAllOfSchemas();

			Schema parentSchema = allOfSchemas.get(0);

			if (parentSchema.getReference() != null) {
				String parentSchemaReference = parentSchema.getReference();

				parentClass = parentSchemaReference.substring(
					parentSchemaReference.lastIndexOf('/') + 1);

				imports.add(Collections.singletonMap("classname", parentClass));

				for (Schema additionalSchema : schema.getAllOfSchemas()) {
					if (additionalSchema.getPropertySchemas() != null) {
						Map<String, Schema> propertySchemas =
							additionalSchema.getPropertySchemas();

						propertySchemas.forEach(
							(propName, propSchema) -> schemaProperties.add(
								HashMapBuilder.<String, Object>put(
									"name",
									StringUtil.replace(
										propName, '-', StringPool.UNDERLINE)
								).put(
									"type",
									_getTypeScriptType(propSchema, imports)
								).build()));
					}
				}
			}
		}

		if (schema.getPropertySchemas() != null) {
			Map<String, Schema> propertySchemas = schema.getPropertySchemas();

			propertySchemas.forEach(
				(propName, propSchema) -> schemaProperties.add(
					HashMapBuilder.<String, Object>put(
						"name",
						StringUtil.replace(propName, '-', StringPool.UNDERLINE)
					).put(
						"type", _getTypeScriptType(propSchema, imports)
					).build()));
		}

		return HashMapBuilder.<String, Object>put(
			"description", schema.getDescription()
		).put(
			"discriminator",
			() -> {
				if (schema.getDiscriminator() == null) {
					return null;
				}

				Discriminator discriminator = schema.getDiscriminator();

				String discriminatorPropName = discriminator.getPropertyName();

				if (Validator.isNull(discriminatorPropName)) {
					return null;
				}

				return discriminatorPropName;
			}
		).put(
			"imports",
			() -> {
				if (imports.isEmpty()) {
					return null;
				}

				return new ArrayList<>(imports);
			}
		).put(
			"modelName", modelName
		).put(
			"parent", parentClass
		).put(
			"properties", schemaProperties
		).build();
	}

	private static Map<String, Object> _buildOperationDataMap(
		ConfigYAML configYAML, OpenAPIYAML openAPIYAML, Operation operation,
		String path) {

		Set<Map<String, String>> imports = new HashSet<>();
		Map<ResponseCode, Response> responses = operation.getResponses();

		Map<String, Object> operationDataMap =
			HashMapBuilder.<String, Object>put(
				"httpMethod",
				StringUtil.toUpperCase(
					OpenAPIParserUtil.getHTTPMethod(operation))
			).put(
				"nickname", operation.getOperationId()
			).put(
				"notes", operation.getDescription()
			).put(
				"path",
				StringBundler.concat(
					configYAML.getApplication(
					).getBaseURI(),
					"/",
					openAPIYAML.getInfo(
					).getVersion(),
					path)
			).put(
				"produces",
				() -> {
					if (responses == null) {
						return null;
					}

					Set<String> produces = new LinkedHashSet<>();

					for (Response response : responses.values()) {
						Map<String, Content> content = response.getContent();

						if (content != null) {
							produces.addAll(content.keySet());
						}
					}

					if (produces.isEmpty()) {
						return null;
					}

					return new ArrayList<>(produces);
				}
			).put(
				"returnType",
				() -> {
					if (responses == null) {
						return null;
					}

					for (Map.Entry<ResponseCode, Response> entry :
							responses.entrySet()) {

						ResponseCode responseCode = entry.getKey();

						if (!Objects.equals(responseCode.getHttpCode(), 200)) {
							continue;
						}

						Response response = entry.getValue();

						Map<String, Content> contentMap = response.getContent();

						if ((contentMap == null) || contentMap.isEmpty()) {
							continue;
						}

						Collection<Content> contents = contentMap.values();

						Iterator<Content> iterator = contents.iterator();

						Content content = iterator.next();

						if ((content == null) ||
							(content.getSchema() == null)) {

							continue;
						}

						return _getTypeScriptType(content.getSchema(), imports);
					}

					return null;
				}
			).build();

		Collection<Map<String, Object>> allParams = _getAllOperationParams(
			operation, operationDataMap, imports);

		if (!allParams.isEmpty()) {
			operationDataMap.put("allParams", allParams);
		}

		if (!imports.isEmpty()) {
			operationDataMap.put("imports", new ArrayList<>(imports));
		}

		return operationDataMap;
	}

	private static void _createBuildGradleFile(
			File baseClientDir, List<File> files)
		throws Exception {

		File file = new File(baseClientDir, "build.gradle");

		files.add(file);

		FileUtil.write(file, StringPool.BLANK);
	}

	private static void _createFile(
			Map<String, Object> context, ConfigYAML configYAML,
			File copyrightFile, List<File> files, String templateName,
			String path)
		throws Exception {

		File file = new File(path);

		files.add(file);

		if (context != null) {
			context = HashMapBuilder.<String, Object>putAll(
				context
			).put(
				"configYAML", configYAML
			).build();
		}
		else {
			context = Collections.singletonMap("configYAML", configYAML);
		}

		FileUtil.write(
			file,
			FreeMarkerUtil.processTemplate(
				copyrightFile, FileUtil.getCopyrightYear(file), templateName,
				context));
	}

	private static void _createNodeScriptsConfigFile(
			File basePath, List<File> files)
		throws Exception {

		File file = new File(basePath, "node-scripts.config.js");

		files.add(file);

		FileUtil.write(
			file,
			FreeMarkerUtil.processTemplate(
				null, null, "typescript/node_scripts_config_js", null));
	}

	private static void _createPackageJSONFile(File basePath, List<File> files)
		throws Exception {

		File file = new File(basePath, "package.json");

		files.add(file);

		FileUtil.write(
			file,
			FreeMarkerUtil.processTemplate(
				null, null, "typescript/package_json",
				HashMapBuilder.<String, Object>put(
					"clientName", basePath.getName()
				).build()));
	}

	private static Collection<Map<String, Object>> _getAllOperationParams(
		Operation operation, Map<String, Object> operationDataMap,
		Set<Map<String, String>> imports) {

		List<Map<String, Object>> allParametersData = new ArrayList<>();
		Map<String, List<Map<String, Object>>> typeParametersData =
			new HashMap<>();

		if (operation.getParameters() != null) {
			for (Parameter parameter : operation.getParameters()) {
				Map<String, Object> parameterData =
					HashMapBuilder.<String, Object>put(
						"dataType",
						_getTypeScriptType(parameter.getSchema(), imports)
					).put(
						"name",
						StringUtil.replace(
							parameter.getName(), '-', StringPool.UNDERLINE)
					).put(
						"required",
						Validator.isNotNull(parameter.isRequired()) &&
						parameter.isRequired()
					).build();

				allParametersData.add(parameterData);

				List<Map<String, Object>> parametersData =
					typeParametersData.computeIfAbsent(
						parameter.getIn() + "Params", k -> new ArrayList<>());

				parametersData.add(parameterData);
			}
		}

		RequestBody requestBody = operation.getRequestBody();

		if (requestBody != null) {
			Map<String, Content> content = requestBody.getContent();

			if ((content != null) && !content.isEmpty()) {
				Collection<Content> contents = content.values();

				Iterator<Content> iterator = contents.iterator();

				Content firstBodyContent = iterator.next();

				if (firstBodyContent != null) {
					Schema schema = firstBodyContent.getSchema();

					if (schema != null) {
						String typeScriptType = _getTypeScriptType(
							schema, imports);

						if (Validator.isNull(schema.getReference())) {
							typeScriptType = "body";
						}

						// TODO: Retrieve 'required' property inside requestBody

						Map<String, Object> bodyParam =
							HashMapBuilder.<String, Object>put(
								"dataType", _getTypeScriptType(schema, imports)
							).put(
								"name",
								StringUtil.replace(
									typeScriptType, '-', StringPool.UNDERLINE)
							).put(
								"required", false
							).build();

						allParametersData.add(bodyParam);
						operationDataMap.put("bodyParam", bodyParam);
					}
				}
			}
		}

		typeParametersData.forEach(
			(key, value) -> {
				if (!value.isEmpty()) {
					operationDataMap.put(key, value);
				}
			});

		return allParametersData;
	}

	private static String _getTypeScriptType(
		Schema schema, Set<Map<String, String>> imports) {

		if (schema == null) {
			return "any";
		}

		if (schema.getReference() != null) {
			String schemaReference = schema.getReference();

			String typeName = schemaReference.substring(
				schemaReference.lastIndexOf('/') + 1);

			if (imports != null) {
				imports.add(Collections.singletonMap("classname", typeName));
			}

			return typeName;
		}

		String schemaType = schema.getType();

		if (schemaType.equals("array")) {
			Items items = schema.getItems();

			String nestedType = _getTypeScriptType(items.toSchema(), imports);

			return "Array<" + nestedType + ">";
		}
		else if (schemaType.equals("boolean")) {
			return "boolean";
		}
		else if (schemaType.equals("integer") || schemaType.equals("number")) {
			return "number";
		}
		else if (schemaType.equals("object")) {
			if (schema.getAdditionalPropertySchema() != null) {
				Schema valueSchema = schema.getAdditionalPropertySchema();

				if (valueSchema.getAdditionalPropertySchema() != null) {
					String typeScriptType = _getTypeScriptType(
						valueSchema.getAdditionalPropertySchema(), imports);

					return "{ [key: string]: { [key: string]: " +
						typeScriptType + "; }; }";
				}

				return "{ [key: string]: " +
					_getTypeScriptType(valueSchema, imports) + "; }";
			}

			return "object";
		}
		else if (schemaType.equals("permission")) {
			if (imports != null) {
				imports.add(
					Collections.singletonMap("classname", "Permission"));
			}

			return "Permission";
		}
		else if (schemaType.equals("string")) {
			List<String> enumValues = schema.getEnumValues();

			if (ListUtil.isNotNull(enumValues)) {
				StringBuilder sb = new StringBuilder();

				for (String value : enumValues) {
					if (sb.length() > 0) {
						sb.append(" | ");
					}

					sb.append("'");
					sb.append(value);
					sb.append("'");
				}

				return sb.toString();
			}

			String schemaFormat = schema.getFormat();

			if (Validator.isNotNull(schemaFormat) &&
				(schemaFormat.equals("date") ||
				 schemaFormat.equals("date-time"))) {

				return "Date";
			}

			return "string";
		}

		return "any";
	}

}