/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.portal.tools.rest.builder.internal.typescript;

import com.liferay.petra.string.CharPool;
import com.liferay.petra.string.StringBundler;
import com.liferay.petra.string.StringPool;
import com.liferay.portal.kernel.util.HashMapBuilder;
import com.liferay.portal.kernel.util.ListUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.portal.kernel.util.StringUtil_IW;
import com.liferay.portal.kernel.util.Validator;
import com.liferay.portal.tools.rest.builder.internal.freemarker.tool.FreeMarkerTool;
import com.liferay.portal.tools.rest.builder.internal.freemarker.tool.java.JavaMethodSignature;
import com.liferay.portal.tools.rest.builder.internal.freemarker.tool.java.parser.ResourceOpenAPIParser;
import com.liferay.portal.tools.rest.builder.internal.freemarker.tool.java.parser.util.OpenAPIParserUtil;
import com.liferay.portal.tools.rest.builder.internal.freemarker.util.FreeMarkerUtil;
import com.liferay.portal.tools.rest.builder.internal.util.FileUtil;
import com.liferay.portal.tools.rest.builder.internal.yaml.config.Application;
import com.liferay.portal.tools.rest.builder.internal.yaml.config.ConfigYAML;
import com.liferay.portal.tools.rest.builder.internal.yaml.openapi.Components;
import com.liferay.portal.tools.rest.builder.internal.yaml.openapi.Content;
import com.liferay.portal.tools.rest.builder.internal.yaml.openapi.Discriminator;
import com.liferay.portal.tools.rest.builder.internal.yaml.openapi.Info;
import com.liferay.portal.tools.rest.builder.internal.yaml.openapi.Items;
import com.liferay.portal.tools.rest.builder.internal.yaml.openapi.OpenAPIYAML;
import com.liferay.portal.tools.rest.builder.internal.yaml.openapi.Operation;
import com.liferay.portal.tools.rest.builder.internal.yaml.openapi.Parameter;
import com.liferay.portal.tools.rest.builder.internal.yaml.openapi.PathItem;
import com.liferay.portal.tools.rest.builder.internal.yaml.openapi.RequestBody;
import com.liferay.portal.tools.rest.builder.internal.yaml.openapi.Response;
import com.liferay.portal.tools.rest.builder.internal.yaml.openapi.ResponseCode;
import com.liferay.portal.tools.rest.builder.internal.yaml.openapi.Schema;

import java.io.File;

import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Iterator;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Set;

/**
 * @author Daniel Raposo
 */
public class TypeScriptClientUtil {

	public static void generateTypeScriptClient(
			File configDir, ConfigYAML configYAML, File copyrightFile,
			String yamlString)
		throws Exception {

		File baseClientDir = new File(
			StringUtil.removeLast(configDir.getPath(), "-impl") + "-client-js");
		List<File> files = new ArrayList<>();

		_createBuildGradleFile(baseClientDir, files);
		_createNodeScriptsConfigFile(baseClientDir, files);
		_createPackageJSONFile(baseClientDir, files);

		OpenAPIYAML openAPIYAML = OpenAPIParserUtil.loadOpenAPIYAML(
			_addAutogeneratedVulcanSchemas(configYAML, yamlString));

		Map<String, Map<String, Object>> apiContexts = _buildAPIContexts(
			configYAML, openAPIYAML);

		for (Map.Entry<String, Map<String, Object>> entry :
				apiContexts.entrySet()) {

			_createFile(
				entry.getValue(), configYAML, copyrightFile, files,
				"typescript/api",
				StringBundler.concat(
					baseClientDir.getPath(), "/src/node/api/",
					StringUtil.lowerCaseFirstLetter(entry.getKey()), "Api.ts"));
		}

		_createFile(
			null, configYAML, copyrightFile, files, "typescript/api_global",
			baseClientDir.getPath() + "/src/node/api.ts");
		_createFile(
			Collections.singletonMap("apiContexts", apiContexts.values()),
			configYAML, copyrightFile, files, "typescript/apis",
			baseClientDir.getPath() + "/src/node/api/apis.ts");

		Components components = openAPIYAML.getComponents();

		Map<String, Schema> schemas = components.getSchemas();

		if (schemas != null) {
			for (Map.Entry<String, Schema> entry : schemas.entrySet()) {
				_createFile(
					_buildModelContext(entry.getKey(), entry.getValue()),
					configYAML, copyrightFile, files, "typescript/model",
					StringBundler.concat(
						baseClientDir.getPath(), "/src/node/model/",
						StringUtil.lowerCaseFirstLetter(entry.getKey()),
						".ts"));
			}
		}

		_createFile(
			Collections.singletonMap("schemaMap", schemas), configYAML,
			copyrightFile, files, "typescript/models",
			baseClientDir.getPath() + "/src/node/model/models.ts");

		FileUtil.deleteFiles(baseClientDir.getPath(), files);
	}

	private static String _addAutogeneratedVulcanSchemas(
			ConfigYAML configYAML, String yamlString)
		throws Exception {

		OpenAPIYAML openAPIYAML = OpenAPIParserUtil.loadOpenAPIYAML(yamlString);
		Set<String> processedSchemaNames = new HashSet<>();

		FreeMarkerTool freeMarkerTool = FreeMarkerTool.getInstance();

		Map<String, Schema> schemas = freeMarkerTool.getSchemas(openAPIYAML);

		for (String schemaName : schemas.keySet()) {
			List<JavaMethodSignature> javaMethodSignatures =
				freeMarkerTool.getResourceJavaMethodSignatures(
					configYAML, openAPIYAML, schemaName);

			for (JavaMethodSignature javaMethodSignature :
					ResourceOpenAPIParser.
						getResourceGetPageJavaMethodSignatures(
							javaMethodSignatures)) {

				String returnType = StringUtil.removeSubstrings(
					javaMethodSignature.getReturnType(),
					"com.liferay.portal.vulcan.pagination.Page<", ">");

				String returnSchemaName = StringUtil.extractLast(
					returnType, ".");

				if (processedSchemaNames.add(returnSchemaName)) {
					if (processedSchemaNames.add("Facet")) {
						yamlString = _addSchema(
							FreeMarkerUtil.processTemplate(
								null, null, "facet_yaml", null),
							yamlString);
					}

					yamlString = _addSchema(
						FreeMarkerUtil.processTemplate(
							null, null, "page_yaml",
							HashMapBuilder.<String, Object>put(
								"schemaName", returnSchemaName
							).build()),
						yamlString);

					if (StringUtil.equals(
							"com.liferay.portal.vulcan.permission.Permission",
							returnType)) {

						yamlString = _addSchema(
							FreeMarkerUtil.processTemplate(
								null, null, "permission_yaml", null),
							yamlString);
					}
				}

				int index = StringUtil.indexOfAny(
					yamlString,
					new String[] {
						"\"" + javaMethodSignature.getPath() + "\":",
						" " + javaMethodSignature.getPath() + ":"
					});

				String httpMethod = OpenAPIParserUtil.getHTTPMethod(
					javaMethodSignature.getOperation());

				index = yamlString.indexOf(httpMethod + ":", index);

				String oldYAMLString = yamlString.substring(
					index, yamlString.indexOf("tags:", index));

				String newYAMLString = oldYAMLString.replaceAll(
					StringBundler.concat(
						"schema:\n([ \t]+)items:\n[ \t]+",
						"\\$ref: \"#/components/schemas/", returnSchemaName,
						"\"\n[ \t]+type: array"),
					StringBundler.concat(
						"schema:\n$1\\$ref: \"#/components/schemas/Page",
						returnSchemaName, "\""));

				yamlString = StringUtil.replace(
					yamlString, oldYAMLString, newYAMLString);
			}
		}

		return yamlString;
	}

	private static String _addSchema(
		String schemaYAMLString, String yamlString) {

		schemaYAMLString = StringUtil.replace(
			schemaYAMLString, new String[] {"$", "\t", "\n"},
			new String[] {"\\$", "$1", "\n$1$1"});

		return yamlString.replaceAll(
			"([ \\t]+)schemas:", "$1schemas:\n$1$1" + schemaYAMLString);
	}

	private static Map<String, Map<String, Object>> _buildAPIContexts(
		ConfigYAML configYAML, OpenAPIYAML openAPIYAML) {

		Map<String, Map<String, Object>> apiContexts = new HashMap<>();

		Map<String, Set<String>> importsMap = new HashMap<>();
		Map<String, List<Map<String, Object>>> operationDatasMap =
			new HashMap<>();

		Map<String, PathItem> pathItems = openAPIYAML.getPathItems();

		for (Map.Entry<String, PathItem> entry : pathItems.entrySet()) {
			for (Operation operation :
					OpenAPIParserUtil.getOperations(entry.getValue())) {

				List<String> tags = operation.getTags();

				List<Map<String, Object>> operationDatas =
					operationDatasMap.computeIfAbsent(
						tags.get(0), tag -> new ArrayList<>());

				operationDatas.add(
					_buildOperationData(
						configYAML,
						importsMap.computeIfAbsent(
							tags.get(0), tag -> new HashSet<>()),
						openAPIYAML, operation, entry.getKey()));
			}
		}

		for (Map.Entry<String, List<Map<String, Object>>> entry :
				operationDatasMap.entrySet()) {

			// TODO Rename "classname" to "className"

			apiContexts.put(
				entry.getKey(),
				HashMapBuilder.<String, Object>put(
					"classname", entry.getKey() + "Api"
				).put(
					"imports",
					importsMap.getOrDefault(entry.getKey(), new HashSet<>())
				).put(
					"operationsData", entry.getValue()
				).build());
		}

		return apiContexts;
	}

	private static Map<String, Object> _buildModelContext(
		String modelName, Schema schema) {

		Set<String> imports = new HashSet<>();
		String parentClass = null;
		List<Map<String, Object>> properties = new ArrayList<>();

		if (schema.getAllOfSchemas() != null) {
			List<Schema> allOfSchemas = schema.getAllOfSchemas();

			Schema parentSchema = allOfSchemas.get(0);

			if (parentSchema.getReference() != null) {
				String parentSchemaReference = parentSchema.getReference();

				parentClass = parentSchemaReference.substring(
					parentSchemaReference.lastIndexOf('/') + 1);

				imports.add(parentClass);

				for (Schema curSchema : schema.getAllOfSchemas()) {
					if (curSchema.getPropertySchemas() == null) {
						continue;
					}

					// TODO Rename "type" to "dataType"

					Map<String, Schema> propertySchemas =
						curSchema.getPropertySchemas();

					propertySchemas.forEach(
						(name, propertySchema) -> properties.add(
							HashMapBuilder.<String, Object>put(
								"name",
								StringUtil.replace(
									name, '-', CharPool.UNDERLINE)
							).put(
								"type", _getDataType(propertySchema, imports)
							).build()));
				}
			}
		}

		// TODO Rename "imports" to "importClasses"

		Map<String, Schema> propertySchemas = schema.getPropertySchemas();

		if (propertySchemas != null) {
			propertySchemas.forEach(
				(name, propertySchema) -> properties.add(
					HashMapBuilder.<String, Object>put(
						"name",
						StringUtil.replace(name, '-', CharPool.UNDERLINE)
					).put(
						"type", _getDataType(propertySchema, imports)
					).build()));
		}

		return HashMapBuilder.<String, Object>put(
			"description", schema.getDescription()
		).put(
			"discriminator",
			() -> {
				Discriminator discriminator = schema.getDiscriminator();

				if (discriminator == null) {
					return null;
				}

				String propertyName = discriminator.getPropertyName();

				if (Validator.isNull(propertyName)) {
					return null;
				}

				return propertyName;
			}
		).put(
			"imports", imports
		).put(
			"modelName", modelName
		).put(
			"parentClass", parentClass
		).put(
			"properties", properties
		).build();
	}

	private static Map<String, Object> _buildOperationData(
		ConfigYAML configYAML, Set<String> imports, OpenAPIYAML openAPIYAML,
		Operation operation, String path) {

		Map<ResponseCode, Response> responses = operation.getResponses();

		return HashMapBuilder.<String, Object>put(
			"description", operation.getDescription()
		).put(
			"httpMethod",
			StringUtil.toUpperCase(OpenAPIParserUtil.getHTTPMethod(operation))
		).put(
			"operationId", operation.getOperationId()
		).put(
			"parameters", _getParameterDatas(operation, imports)
		).put(
			"path",
			() -> {
				Application application = configYAML.getApplication();
				Info info = openAPIYAML.getInfo();

				return StringBundler.concat(
					application.getBaseURI(), "/", info.getVersion(), path);
			}
		).put(
			"responseContentTypes",
			() -> {
				if (responses == null) {
					return null;
				}

				Set<String> produces = new LinkedHashSet<>();

				for (Response response : responses.values()) {
					Map<String, Content> content = response.getContent();

					if (content != null) {
						produces.addAll(content.keySet());
					}
				}

				if (produces.isEmpty()) {
					return null;
				}

				return produces;
			}
		).put(
			"returnDataType",
			() -> {
				if (responses == null) {
					return null;
				}

				for (Map.Entry<ResponseCode, Response> entry :
						responses.entrySet()) {

					ResponseCode responseCode = entry.getKey();

					if (!Objects.equals(responseCode.getHttpCode(), 200)) {
						continue;
					}

					Response response = entry.getValue();

					Map<String, Content> contentsMap = response.getContent();

					if ((contentsMap == null) || contentsMap.isEmpty()) {
						continue;
					}

					Collection<Content> contents = contentsMap.values();

					Iterator<Content> iterator = contents.iterator();

					Content content = iterator.next();

					if ((content == null) || (content.getSchema() == null)) {
						continue;
					}

					return _getDataType(content.getSchema(), imports);
				}

				return null;
			}
		).build();
	}

	private static void _createBuildGradleFile(
			File baseClientDir, List<File> files)
		throws Exception {

		File file = new File(baseClientDir, "build.gradle");

		files.add(file);

		FileUtil.write(file, StringPool.BLANK);
	}

	private static void _createFile(
			Map<String, Object> context, ConfigYAML configYAML,
			File copyrightFile, List<File> files, String name, String path)
		throws Exception {

		File file = new File(path);

		files.add(file);

		if (context != null) {
			context = HashMapBuilder.<String, Object>putAll(
				context
			).put(
				"configYAML", configYAML
			).put(
				"stringUtil", StringUtil_IW.getInstance()
			).build();
		}
		else {
			context = Collections.singletonMap("configYAML", configYAML);
		}

		FileUtil.write(
			file,
			FreeMarkerUtil.processTemplate(
				copyrightFile, FileUtil.getCopyrightYear(file), name, context));
	}

	private static void _createNodeScriptsConfigFile(
			File basePath, List<File> files)
		throws Exception {

		File file = new File(basePath, "node-scripts.config.js");

		files.add(file);

		FileUtil.write(
			file,
			FreeMarkerUtil.processTemplate(
				null, null, "typescript/node_scripts_config_js", null));
	}

	private static void _createPackageJSONFile(File basePath, List<File> files)
		throws Exception {

		File file = new File(basePath, "package.json");

		files.add(file);

		FileUtil.write(
			file,
			FreeMarkerUtil.processTemplate(
				null, null, "typescript/package_json",
				HashMapBuilder.<String, Object>put(
					"clientName", basePath.getName()
				).build()));
	}

	private static String _getDataType(Schema schema, Set<String> imports) {
		if (schema == null) {
			return "any";
		}

		if (schema.getReference() != null) {
			String schemaReference = schema.getReference();

			String dataType = schemaReference.substring(
				schemaReference.lastIndexOf('/') + 1);

			imports.add(dataType);

			return dataType;
		}

		String type = schema.getType();

		if (type.equals("array")) {
			Items items = schema.getItems();

			return "Array<" + _getDataType(items.toSchema(), imports) + ">";
		}
		else if (type.equals("boolean")) {
			return "boolean";
		}
		else if (type.equals("integer") || type.equals("number")) {
			return "number";
		}
		else if (type.equals("object")) {
			Schema additionalPropertySchema =
				schema.getAdditionalPropertySchema();

			if (additionalPropertySchema == null) {
				return "object";
			}

			if (additionalPropertySchema.getAdditionalPropertySchema() !=
					null) {

				String dataType = _getDataType(
					additionalPropertySchema.getAdditionalPropertySchema(),
					imports);

				return "{[key: string]: {[key: string]: " + dataType + ";};}";
			}

			return "{[key: string]: " +
				_getDataType(additionalPropertySchema, imports) + ";}";
		}
		else if (type.equals("permission")) {
			imports.add("Permission");

			return "Permission";
		}
		else if (type.equals("string")) {
			List<String> enumValues = schema.getEnumValues();

			if (ListUtil.isNotNull(enumValues)) {
				StringBuilder sb = new StringBuilder();

				for (String value : enumValues) {
					if (sb.length() > 0) {
						sb.append(" | ");
					}

					sb.append("'");
					sb.append(value);
					sb.append("'");
				}

				return sb.toString();
			}

			String schemaFormat = schema.getFormat();

			if (Validator.isNotNull(schemaFormat) &&
				(schemaFormat.equals("date") ||
				 schemaFormat.equals("date-time"))) {

				return "Date";
			}

			return "string";
		}

		return "any";
	}

	private static Collection<Map<String, Object>> _getParameterDatas(
		Operation operation, Set<String> imports) {

		List<Map<String, Object>> parameterDatas = new ArrayList<>();

		if (operation.getParameters() != null) {
			for (Parameter parameter : operation.getParameters()) {
				parameterDatas.add(
					HashMapBuilder.<String, Object>put(
						"dataType", _getDataType(parameter.getSchema(), imports)
					).put(
						"name",
						StringUtil.replace(
							parameter.getName(), '-', StringPool.UNDERLINE)
					).put(
						"required",
						Validator.isNotNull(parameter.isRequired()) &&
						parameter.isRequired()
					).put(
						"type", parameter.getIn()
					).build());
			}
		}

		RequestBody requestBody = operation.getRequestBody();

		if (requestBody != null) {
			Map<String, Content> content = requestBody.getContent();

			if ((content != null) && !content.isEmpty()) {
				Collection<Content> contents = content.values();

				Iterator<Content> iterator = contents.iterator();

				Content firstBodyContent = iterator.next();

				if (firstBodyContent != null) {
					Schema schema = firstBodyContent.getSchema();

					if (schema != null) {
						String dataType = _getDataType(schema, imports);

						// TODO: Retrieve 'required' property inside requestBody

						parameterDatas.add(
							HashMapBuilder.<String, Object>put(
								"dataType", dataType
							).put(
								"name",
								() -> {
									String replaceString = dataType;

									if (Validator.isNull(
											schema.getReference())) {

										replaceString = "body";
									}

									return StringUtil.replace(
										replaceString, '-',
										StringPool.UNDERLINE);
								}
							).put(
								"required", false
							).put(
								"type", "body"
							).build());
					}
				}
			}
		}

		return parameterDatas;
	}

}