/**
 * Object
 * A Java client JAR is available for use with the group ID \'com.liferay\', artifact ID \'com.liferay.object.admin.rest.client\', and version \'1.0.75\'.
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ObjectViewColumn } from './objectViewColumn';
import { ObjectViewFilterColumn } from './objectViewFilterColumn';
import { ObjectViewSortColumn } from './objectViewSortColumn';

export class ObjectView {
    'actions'?: { [key: string]: { [key: string]: string; }; };
    'dateCreated'?: string;
    'dateModified'?: string;
    'defaultObjectView'?: boolean;
    'id'?: number;
    'name'?: { [key: string]: string; };
    'objectDefinitionExternalReferenceCode'?: string;
    'objectDefinitionId'?: number;
    'objectViewColumns'?: Array<ObjectViewColumn>;
    'objectViewFilterColumns'?: Array<ObjectViewFilterColumn>;
    'objectViewSortColumns'?: Array<ObjectViewSortColumn>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "actions",
            "baseName": "actions",
            "type": "{ [key: string]: { [key: string]: string; }; }"
        },
        {
            "name": "dateCreated",
            "baseName": "dateCreated",
            "type": "string"
        },
        {
            "name": "dateModified",
            "baseName": "dateModified",
            "type": "string"
        },
        {
            "name": "defaultObjectView",
            "baseName": "defaultObjectView",
            "type": "boolean"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "{ [key: string]: string; }"
        },
        {
            "name": "objectDefinitionExternalReferenceCode",
            "baseName": "objectDefinitionExternalReferenceCode",
            "type": "string"
        },
        {
            "name": "objectDefinitionId",
            "baseName": "objectDefinitionId",
            "type": "number"
        },
        {
            "name": "objectViewColumns",
            "baseName": "objectViewColumns",
            "type": "Array<ObjectViewColumn>"
        },
        {
            "name": "objectViewFilterColumns",
            "baseName": "objectViewFilterColumns",
            "type": "Array<ObjectViewFilterColumn>"
        },
        {
            "name": "objectViewSortColumns",
            "baseName": "objectViewSortColumns",
            "type": "Array<ObjectViewSortColumn>"
        }    ];

    static getAttributeTypeMap() {
        return ObjectView.attributeTypeMap;
    }
}

