/**
 * Object
 * A Java client JAR is available for use with the group ID \'com.liferay\', artifact ID \'com.liferay.object.admin.rest.client\', and version \'1.0.75\'.
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ObjectValidationRuleSetting } from './objectValidationRuleSetting';

export class ObjectValidationRule {
    'actions'?: { [key: string]: { [key: string]: string; }; };
    'active'?: boolean;
    'dateCreated'?: string;
    'dateModified'?: string;
    'engine'?: string;
    'engineLabel'?: string;
    'errorLabel'?: { [key: string]: string; };
    'externalReferenceCode'?: string;
    'id'?: number;
    'name'?: { [key: string]: string; };
    'objectDefinitionExternalReferenceCode'?: string;
    'objectDefinitionId'?: number;
    'objectValidationRuleSettings'?: Array<ObjectValidationRuleSetting>;
    'outputType'?: ObjectValidationRule.OutputTypeEnum;
    'script'?: string;
    'system'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "actions",
            "baseName": "actions",
            "type": "{ [key: string]: { [key: string]: string; }; }"
        },
        {
            "name": "active",
            "baseName": "active",
            "type": "boolean"
        },
        {
            "name": "dateCreated",
            "baseName": "dateCreated",
            "type": "string"
        },
        {
            "name": "dateModified",
            "baseName": "dateModified",
            "type": "string"
        },
        {
            "name": "engine",
            "baseName": "engine",
            "type": "string"
        },
        {
            "name": "engineLabel",
            "baseName": "engineLabel",
            "type": "string"
        },
        {
            "name": "errorLabel",
            "baseName": "errorLabel",
            "type": "{ [key: string]: string; }"
        },
        {
            "name": "externalReferenceCode",
            "baseName": "externalReferenceCode",
            "type": "string"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "{ [key: string]: string; }"
        },
        {
            "name": "objectDefinitionExternalReferenceCode",
            "baseName": "objectDefinitionExternalReferenceCode",
            "type": "string"
        },
        {
            "name": "objectDefinitionId",
            "baseName": "objectDefinitionId",
            "type": "number"
        },
        {
            "name": "objectValidationRuleSettings",
            "baseName": "objectValidationRuleSettings",
            "type": "Array<ObjectValidationRuleSetting>"
        },
        {
            "name": "outputType",
            "baseName": "outputType",
            "type": "ObjectValidationRule.OutputTypeEnum"
        },
        {
            "name": "script",
            "baseName": "script",
            "type": "string"
        },
        {
            "name": "system",
            "baseName": "system",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return ObjectValidationRule.attributeTypeMap;
    }
}

export namespace ObjectValidationRule {
    export enum OutputTypeEnum {
        FullValidation = <any> 'fullValidation',
        PartialValidation = <any> 'partialValidation'
    }
}
