/**
 * Object
 * A Java client JAR is available for use with the group ID \'com.liferay\', artifact ID \'com.liferay.object.admin.rest.client\', and version \'1.0.75\'.
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class ObjectViewFilterColumn {
    'filterType'?: ObjectViewFilterColumn.FilterTypeEnum;
    'id'?: number;
    'json'?: string;
    'objectFieldName'?: string;
    'valueSummary'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "filterType",
            "baseName": "filterType",
            "type": "ObjectViewFilterColumn.FilterTypeEnum"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "json",
            "baseName": "json",
            "type": "string"
        },
        {
            "name": "objectFieldName",
            "baseName": "objectFieldName",
            "type": "string"
        },
        {
            "name": "valueSummary",
            "baseName": "valueSummary",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ObjectViewFilterColumn.attributeTypeMap;
    }
}

export namespace ObjectViewFilterColumn {
    export enum FilterTypeEnum {
        Excludes = <any> 'excludes',
        Includes = <any> 'includes'
    }
}
