/**
 * Object
 * A Java client JAR is available for use with the group ID \'com.liferay\', artifact ID \'com.liferay.object.admin.rest.client\', and version \'1.0.75\'.
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ObjectLayoutBox } from './objectLayoutBox';

export class ObjectLayoutTab {
    'id'?: number;
    'name'?: { [key: string]: string; };
    'objectLayoutBoxes'?: Array<ObjectLayoutBox>;
    'objectRelationshipExternalReferenceCode'?: string;
    'objectRelationshipId'?: number;
    'priority'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "{ [key: string]: string; }"
        },
        {
            "name": "objectLayoutBoxes",
            "baseName": "objectLayoutBoxes",
            "type": "Array<ObjectLayoutBox>"
        },
        {
            "name": "objectRelationshipExternalReferenceCode",
            "baseName": "objectRelationshipExternalReferenceCode",
            "type": "string"
        },
        {
            "name": "objectRelationshipId",
            "baseName": "objectRelationshipId",
            "type": "number"
        },
        {
            "name": "priority",
            "baseName": "priority",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return ObjectLayoutTab.attributeTypeMap;
    }
}

