/**
 * Object
 * A Java client JAR is available for use with the group ID \'com.liferay\', artifact ID \'com.liferay.object.admin.rest.client\', and version \'1.0.75\'.
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ObjectState } from './objectState';

export class ObjectStateFlow {
    'id'?: number;
    'objectStates'?: Array<ObjectState>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "objectStates",
            "baseName": "objectStates",
            "type": "Array<ObjectState>"
        }    ];

    static getAttributeTypeMap() {
        return ObjectStateFlow.attributeTypeMap;
    }
}

