/**
 * Object
 * A Java client JAR is available for use with the group ID \'com.liferay\', artifact ID \'com.liferay.object.admin.rest.client\', and version \'1.0.75\'.
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ObjectFolderItem } from './objectFolderItem';

export class ObjectFolder {
    'actions'?: { [key: string]: { [key: string]: string; }; };
    'dateCreated'?: string;
    'dateModified'?: string;
    'externalReferenceCode'?: string;
    'id'?: number;
    'label'?: { [key: string]: string; };
    'name'?: string;
    'objectFolderItems'?: Array<ObjectFolderItem>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "actions",
            "baseName": "actions",
            "type": "{ [key: string]: { [key: string]: string; }; }"
        },
        {
            "name": "dateCreated",
            "baseName": "dateCreated",
            "type": "string"
        },
        {
            "name": "dateModified",
            "baseName": "dateModified",
            "type": "string"
        },
        {
            "name": "externalReferenceCode",
            "baseName": "externalReferenceCode",
            "type": "string"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "label",
            "baseName": "label",
            "type": "{ [key: string]: string; }"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "objectFolderItems",
            "baseName": "objectFolderItems",
            "type": "Array<ObjectFolderItem>"
        }    ];

    static getAttributeTypeMap() {
        return ObjectFolder.attributeTypeMap;
    }
}

