/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Facet } from './facet';
import { SiteTestEntity } from './siteTestEntity';

export class PageSiteTestEntity {
    'actions'?: { [key: string]: { [key: string]: string; }; };
    'facets'?: Array<Facet>;
    'items'?: Array<SiteTestEntity>;
    'lastPage'?: number;
    'page'?: number;
    'pageSize'?: number;
    'totalCount'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "actions",
            "baseName": "actions",
            "type": "{ [key: string]: { [key: string]: string; }; }"
        },
        {
            "name": "facets",
            "baseName": "facets",
            "type": "Array<Facet>"
        },
        {
            "name": "items",
            "baseName": "items",
            "type": "Array<SiteTestEntity>"
        },
        {
            "name": "lastPage",
            "baseName": "lastPage",
            "type": "number"
        },
        {
            "name": "page",
            "baseName": "page",
            "type": "number"
        },
        {
            "name": "pageSize",
            "baseName": "pageSize",
            "type": "number"
        },
        {
            "name": "totalCount",
            "baseName": "totalCount",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return PageSiteTestEntity.attributeTypeMap;
    }
}

