/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Permission } from './permission';

export class SiteTestEntity {
    'dateCreated'?: Date;
    'dateModified'?: Date;
    'description'?: string;
    'externalReferenceCode'?: string;
    'id'?: number;
    'permissions'?: Array<Permission>;
    'siteId'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "dateCreated",
            "baseName": "dateCreated",
            "type": "Date"
        },
        {
            "name": "dateModified",
            "baseName": "dateModified",
            "type": "Date"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "externalReferenceCode",
            "baseName": "externalReferenceCode",
            "type": "string"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "permissions",
            "baseName": "permissions",
            "type": "Array<Permission>"
        },
        {
            "name": "siteId",
            "baseName": "siteId",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return SiteTestEntity.attributeTypeMap;
    }
}

