include-and-override=portlet-ext.properties

github.url=

help.center.api.username=
help.center.api.password=
help.center.file.repo.id=
help.center.file.repo.url=
help.center.get.account.api.endpoint=
help.center.jsonws.url=
help.center.ticket.attachment.api.endpoint=
help.center.token.ticket.dir=
help.center.url=

hotfix.mount.path=

info.modify.tickets.list.url=

jenkins.admin.user.token=
jenkins.admin.username=
jenkins.build.with.parameters.path=
jenkins.load.balancer.base.invocation.url=
jenkins.load.balancer.enabled=
jenkins.token=
jenkins.url=

jira.url=

lesa.url=

liferay.users.profile.url=

osb.patcher.account.whitelist=

osb.patcher.agent.jenkins.url=

osb.patcher.build.download.url=

osb.patcher.git.tag.prefix=

osb.patcher.jenkins.requests.enabled=

osb.patcher.liferay.portal.repository=

osb.patcher.pubsub.credential.file.path=
osb.patcher.pubsub.project.id=
osb.patcher.pubsub.subscription.id=

osb.patcher.scanning.enabled=

osb.patcher.shared.request.add.fix.patcher.type=
osb.patcher.shared.request.build.patch.patcher.type=

osb.patcher.status.path=

osb.patcher.status.build.jenkins.path=
osb.patcher.status.build.jenkins.test.path=
osb.patcher.status.build.path=
osb.patcher.status.fix.path=

osb.patcher.tests.enabled=

resource.actions.configs=resource-actions/default.xml

troubleshooting.url=