/**
 * 
 * A Java client JAR is available for use with the group ID \'com.liferay\', artifact ID \'com.liferay.change.tracking.rest.client\', and version \'4.0.1\'.
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Status } from './status';

/**
* Represents a set of changes tracked for a publication.
*/
export class CTCollection {
    'actions'?: { [key: string]: { [key: string]: string; }; };
    /**
    * The publication\'s creation date.
    */
    'dateCreated'?: Date;
    /**
    * The last time any of the publication\'s fields were changed.
    */
    'dateModified'?: Date;
    /**
    * The date that the publication will be published.
    */
    'dateScheduled'?: Date;
    'description'?: string;
    'externalReferenceCode'?: string;
    'id'?: number;
    'name'?: string;
    /**
    * The publication\'s creator.
    */
    'ownerName'?: string;
    'status'?: Status;
    /**
    * Info on when a publication was last published or modified.
    */
    'statusMessage'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "actions",
            "baseName": "actions",
            "type": "{ [key: string]: { [key: string]: string; }; }"
        },
        {
            "name": "dateCreated",
            "baseName": "dateCreated",
            "type": "Date"
        },
        {
            "name": "dateModified",
            "baseName": "dateModified",
            "type": "Date"
        },
        {
            "name": "dateScheduled",
            "baseName": "dateScheduled",
            "type": "Date"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "externalReferenceCode",
            "baseName": "externalReferenceCode",
            "type": "string"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "ownerName",
            "baseName": "ownerName",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "Status"
        },
        {
            "name": "statusMessage",
            "baseName": "statusMessage",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CTCollection.attributeTypeMap;
    }
}

