/**
 * 
 * A Java client JAR is available for use with the group ID \'com.liferay\', artifact ID \'com.liferay.change.tracking.rest.client\', and version \'4.0.1\'.
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Status } from './status';

/**
* Represents publications that have been published.
*/
export class CTProcess {
    'actions'?: { [key: string]: { [key: string]: string; }; };
    'ctCollectionId'?: number;
    /**
    * The publication\'s published date.
    */
    'datePublished'?: Date;
    'description'?: string;
    'id'?: number;
    'name'?: string;
    /**
    * The publication\'s creator.
    */
    'ownerName'?: string;
    'status'?: Status;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "actions",
            "baseName": "actions",
            "type": "{ [key: string]: { [key: string]: string; }; }"
        },
        {
            "name": "ctCollectionId",
            "baseName": "ctCollectionId",
            "type": "number"
        },
        {
            "name": "datePublished",
            "baseName": "datePublished",
            "type": "Date"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "ownerName",
            "baseName": "ownerName",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "Status"
        }    ];

    static getAttributeTypeMap() {
        return CTProcess.attributeTypeMap;
    }
}

