/**
 * 
 * A Java client JAR is available for use with the group ID \'com.liferay\', artifact ID \'com.liferay.change.tracking.rest.client\', and version \'4.0.1\'.
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class FacetValue {
    'numberOfOccurrences'?: number;
    'term'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "numberOfOccurrences",
            "baseName": "numberOfOccurrences",
            "type": "number"
        },
        {
            "name": "term",
            "baseName": "term",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return FacetValue.attributeTypeMap;
    }
}

